bwi_msgs/MultiLevelMapPoint start
bwi_msgs/MultiLevelMapPoint goal
---

uint8 plan_found
string error_message

uint8 use_local_planning

geometry_msgs/Point start_level_goal
geometry_msgs/Point goal_level_start
bwi_msgs/MultiLevelMapLink transition
bool reverse_transition

