#!/usr/bin/env python

import roslib; roslib.load_manifest('bwi_apps')
import rospy

import sys, yaml

# from bwi_msgs.msg import MultiLevelMap

class MapServer:
  def __init__(self):
    rospy.init_node('listener', anonymous=True)

    #get parameters
    self.global_frame_id = rospy.get_param('~global_frame_id', '/map')

    if len(sys.argv) >= 2:
      yaml_file = sys.argv[1]
      try:
        map = yaml.load(open(yaml_file, 'r'))
      except:
        rospy.logfatal("Unable to parse map yaml file. Did you provide the right file: %s" %yaml_file)
        return
    else:
      rospy.logfatal("map yaml file not provided. USAGE: bwi_map_server <map_file")
      return

    print map
      
if __name__ == '__main__':
  MapServer()


    

